### PR TITLE
WIP: Work in sync mode only

### PR DESCRIPTION
**Pull request by abadyan-vonage**
# Description

Work in sync mode only as background jobs don't work well in a serverless environment.
For other environments, it is preferred to use the original unleash client.

Not yet tested.

### CODE REVIEW

**Review by levkaganv — COMMENTED** [review]
IIUC You are fetching flags only on initialization. So we will need to initialize `UnleashClient` each time we wanna call `is_enabled` ? If I'm right then looks like using  `UnleashClient` client this way would work also.

**Comment by abadyan-vonage** [comment]
No, we would initialize the client before each flask request, but all calls to is_enabled after that will be from cache.

**Comment by levkaganv** [comment]
Wouldn't this work the same way without this change ?

**Comment by abadyan-vonage** [comment]
No, because now it takes an unknown amount of time for the background thread to updated the lambda cache (this is what happened to us in qa). Also metrics are pretty much never sent.

**Comment by levkaganv** [comment]
But now when you init the client it gets the flags in the constructor and also created an updated thread. So if you re-init it each time on request it will always get the latest flags info.

**Comment by abadyan-vonage** [comment]
yes, that is true but I also don't want the extra threads and also calling numerous times might not work well.

**Comment by levkaganv** [comment]
Ok got it. And also you send metrics on close :)
LGTM

**Pull request merged**
